# Generated by Django 4.2.3 on 2023-07-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ordens',
            new_name='ordem',
        ),
    ]
